SET(CTEST_PROJECT_NAME "vegapp")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
SET(CTEST_CUSTOM_MAXIMUM_FAILED_TEST_OUTPUT_SIZE 0)

SET (CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}")

SET(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE_CDASH TRUE)
SET (CTEST_DROP_SITE_USER "cdash:azqsC14mAn")
  
SET(CTEST_DROP_SITE "www.alneos.com:9991")
SET(CTEST_DROP_LOCATION "/cdash/submit.php?project=vegapp")

