stages:
  - build
  - test

shbuilding:
  stage: build
  tags:
    - shell
    - irt
    - linux
  before_script:
    - cat /etc/issue
    - whoami
    - pwd
    - hostname
    - export PATH=$PATH:/opt/TOP/ESI/sysworld/v2018.0/GB/
    - which systus
  script:
    - mkdir build
    - cd build
    - /opt/cmake-3.12.3-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=SDebug -DSTATIC_LINKING=ON -DBOOST_ROOT:PATHNAME=/opt/boost-1.65.1 -DRUN_SYSTUS=ON -DCMAKE_C_COMPILER=/opt/gcc-5.5.0/bin/gcc -DCMAKE_CXX_COMPILER=/opt/gcc-5.5.0/bin/g++ -DHDF5_LIBRARIES=/opt/aster/public/hdf5-1.8.14/lib/libhdf5.a -DHDF5_INCLUDE_DIRS=/opt/aster/public/hdf5-1.8.14/include -DMEDFILE_C_LIBRARIES=/opt/aster/public/med-3.3.1/lib/libmedC.a -DMEDFILE_INCLUDE_DIRS=/opt/aster/public/med-3.3.1/include  ..
    - make -j
    - LC_ALL="en_US.UTF-8" ctest -VV .
    - cp ./bin/vegapp /srv/data
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./build/bin/vegapp
    expire_in: 1 day

xbuilding:
  stage: build
  image: docker:dind
  tags:
    - docker
    - irt
  variables:
    XTEST_IMAGE: gitlab/xvegairt
    XTEST_CONTAINER: xvegairt_oncommit
  before_script:
    - apk add --update --no-cache git
    - env | grep ^DOCKER_
    - env | grep ^CI_
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info
  script:
    - docker pull ldallolio/xvegaci
    - docker build -t $XTEST_IMAGE -f Dockerfile_xgitlab .
    - export OUTDIR=$(LC_ALL=en_US.utf8 date +%a)
    - mkdir -p /srv/data/$OUTDIR
    - docker run --rm -v /srv:/srv "$XTEST_IMAGE" sh -c "sudo cp ./bin/vegapp.exe /srv/data/$OUTDIR"
    - cp /srv/data/$OUTDIR/vegapp.exe /srv/data
    - cp /srv/data/$OUTDIR/vegapp.exe ./
    - docker rmi "$XTEST_IMAGE"
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - vegapp.exe
    expire_in: 1 day

esiqual:
  stage: test
  tags:
    - shell
    - irt
    - linux
    - systus
  script:
    - export TOPAZE_PATH=/opt/TOP/ESI/topaze
    - source /opt/TOP/ESI/topazerc.sh
    - export PATH=$PATH:$TOPAZE_BIN
    - cd /srv/data/BDTest_VEGA
    - ./QUALIF_VEGAOK.csh
    - 'grep "Nombre de fichiers passes avec erreur :   0" /srv/data/BDTest_VEGA/BASE_DETESTS/RES_ANG/RAP_ANG/ANG_linux86_64_VEGAOK_Sysworld_V19.0-new.RAPQ'
    - ./QUALIF_VEGANOOK.csh
    - 'grep "Nombre de fichiers passes avec succes :   0" /srv/data/BDTest_VEGA/BASE_DETESTS/RES_ANG/RAP_ANG/ANG_linux86_64_VEGANOOK_Sysworld_V19.0-new.RAPQ'
    - 'grep -vc "*** ERREUR" /srv/data/BDTest_VEGA/BASE_DETESTS/RES_ANG/RAP_ANG/ANG_linux86_64_VEGANOOK_Sysworld_V19.0-new.RAPQ'

nightly_systus:
  stage: test
  tags:
    - shell
    - irt
    - linux
    - systus
  only:
    - schedules
  before_script:
    - export OUTDIR=$(LC_ALL=en_US.utf8 date +%a)
    - export PATH=$PATH:/opt/TOP/ESI/sysworld/v2018.0/GB/
    - mkdir -p /srv/data/$OUTDIR; mkdir -p /srv/data/$OUTDIR/aster; mkdir -p /srv/data/$OUTDIR/systus
  script:
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/systus /srv/data/input/AirbusUseCase/TOP_CAS_AIRBUS_11032019.fem optistruct systus
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/systus -t /srv/data/input/v02_K9Kgen6_simplif/refres/v02_K9Kgen6_simplif.f06 -x 5.0 /srv/data/input/v02_K9Kgen6_simplif/original/v02_K9Kgen6_simplif.fem optistruct systus
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/systus /srv/data/input/Safran_AB_RadiusBlock_v1.fem optistruct systus
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input/AirbusUseCase/TOP_CAS_AIRBUS_11032019.fem optistruct aster
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster -t /srv/data/input/v02_K9Kgen6_simplif/refres/v02_K9Kgen6_simplif.f06 -x 0.05 /srv/data/input/v02_K9Kgen6_simplif/original/v02_K9Kgen6_simplif.fem optistruct aster
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input/Safran_AB_RadiusBlock_v1.fem optistruct aster
    - /srv/data/vegapp -s -o /srv/data/$OUTDIR/aster /srv/data/input/v02_K9Kgen6_rebuild/v02_K9Kgen6_rebuild.fem optistruct aster
    - /srv/data/vegapp -s -o /srv/data/$OUTDIR/systus /srv/data/input/v02_K9Kgen6_rebuild/v02_K9Kgen6_rebuild.fem optistruct systus
    - /srv/data/vegapp -s -o /srv/data/$OUTDIR/aster /srv/data/input/SMOTRenault/SMOTRENAULT.fem optistruct aster
    - /srv/data/vegapp -s -o /srv/data/$OUTDIR/systus /srv/data/input/SMOTRenault/SMOTRENAULT.fem optistruct systus
