stages:
  - build
  - test

building:
  stage: build
  image: docker:dind
  tags:
    - docker
    - irt
  variables:
    TEST_IMAGE: gitlab/vegairt
  before_script:     
    - env | grep ^DOCKER_     
    - env | grep ^CI_     
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info
  script:
    - docker build -t $TEST_IMAGE -f Dockerfile_gitlab .
    - docker run -v /opt:/opt --rm "$TEST_IMAGE" /bin/sh -c "source /home/vega/.bashrc && ctest ."
    - docker rmi "$TEST_IMAGE"

nightly:
  stage: test
  tags:
    - shell
    - irt
  only:
    - schedules
  before_script:
    - whoami
    - pwd
  script:
    - ls /opt
