stages:
  - build

building:
  stage: build
  image: docker:dind
  variables:
    TEST_IMAGE: gitlab/vegairt
  before_script:     
    - env | grep ^DOCKER_     
    - env | grep ^CI_     
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info
  script:
    - docker build $TEST_IMAGE -f Dockerfile_gitlab .
    - docker run --rm $TEST_IMAGE
    - docker rmi "$TEST_IMAGE"
