stages:
  - build

building:
  stage: build
  variables:     
    DOCKER_REPO: stc-2.irt-systemx.local:5000
    DOCKER_HOST: tcp://192.168.26.2:2375
    PUBLIC_TEST_IMAGE: ldallolio/vegaci
  image: sofianinho/dind
  before_script:     
    - env | grep ^DOCKER_     
    - env | grep ^CI_     
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info    
  script:
    - docker login $DOCKER_REPO --username $RUNNER_USERNAME --password $RUNNER_PASSWORD
    - docker pull $PUBLIC_TEST_IMAGE
    - docker run -t --rm $PUBLIC_TEST_IMAGE /bin/sh -c "source /home/vega/.bashrc && git clone --depth=50 --branch=sum2018 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.irt-systemx.fr/TOP/tache-1/prestation/vega.git /home/vega/vegapp && mkdir /home/vega/vegapp/build && cd /home/vega/vegapp/build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j && ctest ."
