stages:
  - build
  - test

shbuilding:
  stage: build
  tags:
    - shell
    - irt
    - linux
  before_script:
    - cat /etc/issue
    - whoami
    - pwd
    - hostname
    - export PATH=$PATH:/opt/TOP/ESI/sysworld/v2018.0/GB/
    - which systus
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=DDebug -DBOOST_ROOT:PATHNAME=/opt/boost-1.69.0 -DRUN_SYSTUS=OFF -DBoost_NO_BOOST_CMAKE=ON -DHDF5_C_LIBRARY_z=/lib/x86_64-linux-gnu/libz.so.1 -DHDF5_ROOT=/opt/aster/public/hdf5-1.10.3 -DMEDFILE_C_LIBRARIES=/opt/aster/public/med-4.0.0/lib/libmedC.so -DMEDFILE_INCLUDE_DIRS=/opt/aster/public/med-4.0.0/include --verbose  ..
    - make -j
    - LC_ALL="en_US.UTF-8" ctest -VV .
    - cp ./bin/vegapp /srv/data
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./build/bin/vegapp
    expire_in: 1 day

.hidden_xbuilding:
  stage: build
  image: docker:dind
  tags:
    - docker
    - irt
  variables:
    XTEST_IMAGE: gitlab/xvegairt
    XTEST_CONTAINER: xvegairt_oncommit
  before_script:
    - apk add --update --no-cache git
    - env | grep ^DOCKER_
    - env | grep ^CI_
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info
  script:
    - docker pull ldallolio/xvegaci
    - docker build -t $XTEST_IMAGE -f Dockerfile_xgitlab .
    - export OUTDIR=$(LC_ALL=en_US.utf8 date +%a)
    - mkdir -p /srv/data/$OUTDIR
    - docker run --rm -v /srv:/srv "$XTEST_IMAGE" sh -c "sudo cp ./bin/vegapp.exe /srv/data/$OUTDIR"
    - cp /srv/data/$OUTDIR/vegapp.exe /srv/data
    - cp /srv/data/$OUTDIR/vegapp.exe ./
    - docker rmi "$XTEST_IMAGE"
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - vegapp.exe
    expire_in: 1 day

.hidden_esiqual:
  stage: test
  tags:
    - shell
    - irt
    - linux
    - systus
  script:
    - export PATH=$PATH:/opt/TOP/ESI2020/sysworld/2020.0/Linux_x86_64/bin
    - cd /srv/data/BDTest_VEGA
    - ./QUALIF_VEGAOK.csh
    - 'grep "Nombre de fichiers passes avec erreur :   0" /srv/data/BDTest_VEGA/BASE_DETESTS/RES_ANG/RAP_ANG/ANG_linux86_64_VEGAOK_Sysworld_V19.0-new.RAPQ'
    - ./QUALIF_VEGANOOK.csh
    - 'grep "Nombre de fichiers passes avec succes :   0" /srv/data/BDTest_VEGA/BASE_DETESTS/RES_ANG/RAP_ANG/ANG_linux86_64_VEGANOOK_Sysworld_V19.0-new.RAPQ'
    - 'grep -vc "*** ERREUR" /srv/data/BDTest_VEGA/BASE_DETESTS/RES_ANG/RAP_ANG/ANG_linux86_64_VEGANOOK_Sysworld_V19.0-new.RAPQ'

.hidden_nightly_systus:
  stage: test
  tags:
    - shell
    - irt
    - linux
    - systus
  only:
    - schedules
  before_script:
    - export OUTDIR=$(LC_ALL=en_US.utf8 date +%a)
    - export PATH=$PATH:/opt/TOP/ESI/sysworld/v2018.0/GB/
    - mkdir -p /srv/data/$OUTDIR; mkdir -p /srv/data/$OUTDIR/aster; mkdir -p /srv/data/$OUTDIR/systus
  script:
    - /srv/data/vegapp --solver-version=2018 -s -o /srv/data/$OUTDIR/systus /srv/data/input/v03_K9Kgen6_rebuild/v03_K9Kgen6_rebuild_analysis_mass_sansHFREQ_sansRESVEC.fem optistruct systus 2>&1 | tee /srv/data/$OUTDIR/systus/v03_K9Kgen6_rebuild_vegapp.log
    - /srv/data/vegapp --run-solver --solver-version=2018 -s -o /srv/data/$OUTDIR/systus /srv/data/input/v03_K9Kgen6_simplif/v03_K9Kgen6_simplif_analysis_mass_sansHFREQ_sansRESVEC.fem optistruct systus 2>&1 | tee /srv/data/$OUTDIR/systus/v03_K9Kgen6_simplif_vegapp.log
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input/v03_K9Kgen6_simplif/v03_K9Kgen6_simplif_analysis_mass_sansHFREQ_sansRESVEC.fem optistruct aster 2>&1 | tee /srv/data/$OUTDIR/aster/v03_K9Kgen6_simplif_vegapp.log
    - /srv/data/vegapp --run-solver --solver-version=2018 -s -o /srv/data/$OUTDIR/systus /srv/data/input/AirbusUseCase/TOP_CAS_AIRBUS_11032019.fem optistruct systus 2>&1 | tee /srv/data/$OUTDIR/systus/TOP_CAS_AIRBUS_11032019_vegapp.log
    - /srv/data/vegapp --run-solver --solver-version=2018 -s -o /srv/data/$OUTDIR/systus /srv/data/input/Safran_AB_RadiusBlock_v1.fem optistruct systus 2>&1 | tee /srv/data/$OUTDIR/systus/Safran_AB_RadiusBlock_v1_vegapp.log
    - /srv/data/vegapp --solver-version=2018 -s -o /srv/data/$OUTDIR/systus /srv/data/input_mod/Safran_AB_RadiusBlock_v2/Safran_AB_RadiusBlock_v2_pbushrepl/Safran_AB_RadiusBlock_v2_pbushrepl.fem  optistruct systus 2>&1 | tee /srv/data/$OUTDIR/systus/Safran_AB_RadiusBlock_v2_pbushrepl_vegapp.log
    - /srv/data/vegapp --run-solver --solver-version=2018 -s -o /srv/data/$OUTDIR/systus -t /srv/data/input_mod/CasTest_Aile_12122019/aile_grav/CasTest_Aile_12122019_ajoutgrav.f06 -x 0.02 /srv/data/input_mod/CasTest_Aile_12122019/aile_grav/CasTest_Aile_12122019_ajoutgrav.bdf nastran systus 2>&1 | tee /srv/data/$OUTDIR/systus/CasTest_Aile_12122019_ajoutgrav_vegapp.log
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input_mod/minirbs/minirbs_vg.fem optistruct aster 2>&1 | tee /srv/data/$OUTDIR/aster/minirbs_vg_vegapp.log
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input/AirbusUseCase/TOP_CAS_AIRBUS_11032019.fem optistruct aster 2>&1 | tee /srv/data/$OUTDIR/aster/TOP_CAS_AIRBUS_11032019_vegapp.log
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster -t /srv/data/input_mod/CasTest_Aile_12122019/aile_grav/CasTest_Aile_12122019_ajoutgrav.f06 -x 0.02 /srv/data/input_mod/CasTest_Aile_12122019/aile_grav/CasTest_Aile_12122019_ajoutgrav.bdf nastran aster 2>&1 | tee /srv/data/$OUTDIR/aster/CasTest_Aile_12122019_ajoutgrav_vegapp.log
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input/Safran_AB_RadiusBlock_v1.fem optistruct aster 2>&1 | tee /srv/data/$OUTDIR/aster/Safran_AB_RadiusBlock_v1_vegapp.log
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input_mod/Safran_AB_RadiusBlock_v2/Safran_AB_RadiusBlock_v2_pbushrepl/Safran_AB_RadiusBlock_v2_pbushrepl.fem  optistruct aster 2>&1 | tee /srv/data/$OUTDIR/aster/Safran_AB_RadiusBlock_v2_pbushrepl_vegapp.log
    - /srv/data/vegapp --solver-version=2018 -s -o /srv/data/$OUTDIR/systus /srv/data/input_mod/v03_K9Kgen6_rebuild/v03_K9Kgen6_rebuild_analysis_mass_sansHFREQ_sansRESVEC_sc1_sc2_sc3.fem optistruct systus 2>&1 | tee /srv/data/$OUTDIR/systus/v03_K9Kgen6_rebuild_sc1_sc2_sc3_vegapp.log
    - /srv/data/vegapp --run-solver -s -o /srv/data/$OUTDIR/aster /srv/data/input_mod/v03_K9Kgen6_rebuild/v03_K9Kgen6_rebuild_analysis_mass_sansHFREQ_sansRESVEC_sc1_sc2_sc3.fem optistruct aster 2>&1 | tee /srv/data/$OUTDIR/aster/v03_K9Kgen6_rebuild_sc1_sc2_sc3_vegapp.log
    - /srv/data/vegapp -s -o /srv/data/$OUTDIR/aster /srv/data/input/SMOTRenault/SMOTRENAULT.fem optistruct aster 2>&1 | tee /srv/data/$OUTDIR/aster/SMOTRENAULT_vegapp.log
    - /srv/data/vegapp -s --solver-version=2018 -o /srv/data/$OUTDIR/systus /srv/data/input/SMOTRenault/SMOTRENAULT.fem optistruct systus 2>&1 | tee /srv/data/$OUTDIR/systus/SMOTRENAULT_vegapp.log
