stages:
  - build
  - xbuild
  - test

shbuilding:
  stage: build
  tags:
    - shell
    - irt
    - linux
  before_script:
    - cat /etc/issue
    - whoami
    - pwd
    - hostname
    - export PATH=$PATH:/opt/TOP/ESI/sysworld/v2018.0/GB/
    - which systus
  script:
    - mkdir build
    - cd build
    - cmake -D RUN_SYSTUS=ON -DHDF5_LIBRARIES=/opt/aster/public/hdf5-1.8.14/lib/libhdf5.a -DHDF5_INCLUDE_DIRS=/opt/aster/public/hdf5-1.8.14/include -DMEDFILE_C_LIBRARIES=/opt/aster/public/med-3.3.1/lib/libmedC.a -DMEDFILE_INCLUDE_DIRS=/opt/aster/public/med-3.3.1/include  ..
    - make -j
    - LC_ALL="en_US.UTF-8" ctest -VV .
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./build/bin/vegapp
    expire_in: 1 day

xbuilding:
  stage: xbuild
  image: docker:dind
  tags:
    - docker
    - irt
  variables:
    XTEST_IMAGE: gitlab/xvegairt
    XTEST_CONTAINER: xvegairt_oncommit
  before_script:
    - apk add --update --no-cache git
    - export OUTDIR=$(git show -s --format="%cd_%h" --date=format:'%Y-%m-%d_%H%M' $CI_COMMIT_SHA)
    - env | grep ^DOCKER_
    - env | grep ^CI_
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info
  script:
    - docker pull ldallolio/xvegaci
    - docker build -t $XTEST_IMAGE -f Dockerfile_xgitlab .
    - export OUTDIR=$(git show -s --format="%cd_%h" --date=format:'%Y-%m-%d_%H%M' $CI_COMMIT_SHA)
    - mkdir -p /srv/data/$OUTDIR
    - docker run --rm -v /srv:/srv "$XTEST_IMAGE" sh -c "sudo cp ./bin/vegapp.exe /srv/data/$OUTDIR"
    - cp /srv/data/$OUTDIR/vegapp.exe /srv/data
    - cp /srv/data/$OUTDIR/vegapp.exe ./
    - docker rmi "$XTEST_IMAGE"
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - vegapp.exe
    expire_in: 1 day

nightly:
  stage: test
  tags:
    - shell
    - irt
    - linux
  only:
    - schedules
  before_script:
    - whoami
    - pwd
    - export OUTDIR=$(date +%Y-%m-%d_%H%M)
    - export PATH=$PATH:/opt/TOP/ESI/sysworld/v2018.0/GB/
    - mkdir -p /srv/data/$OUTDIR
    - ls /srv/data
  script:
    - /srv/data/vegapp -s -o /srv/data/$OUTDIR --run-solver /srv/data/input/v02_K9Kgen6_simplif/original/v02_K9Kgen6_simplif.fem optistruct systus
