stages:
  - build
  - test

building:
  stage: build
  image: docker:dind
  tags:
    - docker
    - irt
  variables:
    TEST_IMAGE: gitlab/vegairt
    TEST_CONTAINER: vegairt_oncommit
  before_script:     
    - env | grep ^DOCKER_     
    - env | grep ^CI_     
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info
  script:
    - docker pull ldallolio/vegaci
    - docker build -t $TEST_IMAGE -f Dockerfile_gitlab .
    - docker ps -q --filter "name=$TEST_CONTAINER" | grep -q . && docker rm -fv $TEST_CONTAINER
    - docker run --name "$TEST_CONTAINER" "$TEST_IMAGE" /bin/sh -c "source /home/vega/.bashrc && ctest ."
    - docker cp $TEST_CONTAINER:/home/vega/vegapp/build/bin/vegapp .
    - ls
    - docker rm -f "$TEST_CONTAINER"
    - docker rmi "$TEST_IMAGE"
  artifacts:
    paths:
    - vegapp
    expire_in: 1 day

nightly:
  stage: test
  tags:
    - shell
    - irt
  only:
    - schedules
  before_script:
    - whoami
    - pwd
  script:
    - ls /opt
