stages:
  - build

building:
  stage: build
  variables:     
    DOCKER_REPO: stc-2.irt-systemx.local:5000
    DOCKER_HOST: tcp://192.168.26.2:2375
    PUBLIC_TEST_IMAGE: ldallolio/vegaci
  image: sofianinho/dind
  before_script:     
    - env | grep ^DOCKER_     
    - env | grep ^CI_     
    - cat /etc/issue
    - whoami
    - pwd
    - which docker
    - docker info
  tags:     
    - stc 
    - docker
    - new
  script:
    - ls
