language: cpp

sudo: required
dist: trusty
cache: ccache

services:
  - docker

before_install:
  - docker build -t ldallolio/vegaci .

script:
  - docker run ldallolio/vegaci /bin/sh -c "cd /usr/local/src/vegapp/build; cmake -DCMAKE_BUILD_TYPE=Debug ..; make -j; ctest ."
