language: cpp

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull ldallolio/vegaci

script:
  - docker run -e GITHUB_TOKEN=$GITHUB_TOKEN ldallolio/vegaci /bin/sh -c "source /home/vega/.bashrc && git clone --depth=50 --branch=master https://github.com/Alneos/vega.git /home/vega/vegapp && mkdir /home/vega/vegapp/build && cd /home/vega/vegapp/build && cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_SYSTUS=OFF .. && make -j && ctest -D Experimental ."

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: $TRAVIS_BUILD_DIR/doxydoc/html
  keep-history: true
  on:
    branch: master
