language: cpp

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull ldallolio/vegaci

script:
  - docker run -e GITHUB_TOKEN=$GITHUB_TOKEN ldallolio/vegaci /bin/sh -c "git clone --depth=50 --branch=master https://github.com/Alneos/vega.git /home/vega/vegapp && mkdir /home/vega/vegapp/build && cd /home/vega/vegapp/build && cmake -DHDF5_LIBRARIES=/opt/aster/public/hdf5-1.10.3/lib/libhdf5.a -DHDF5_INCLUDE_DIRS=/opt/aster/public/hdf5-1.10.3/include -DMEDFILE_C_LIBRARIES=/opt/aster/public/med-4.0.0/lib/libmedC.a -DMEDFILE_INCLUDE_DIRS=/opt/aster/public/med-4.0.0/include -DCMAKE_BUILD_TYPE=Debug -DRUN_SYSTUS=OFF .. && make -j2 && ctest -D Experimental ."

