language: cpp

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull ldallolio/vegaci

script:
  - docker run ldallolio/vegaci /bin/sh -c "source /home/vega/.bashrc && git clone --depth=50 --branch=master https://github.com/Alneos/vega.git /home/vega/vegapp && mkdir /home/vega/vegapp/build && cd /home/vega/vegapp/build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j && ctest -D Continuous ."
