language: cpp

sudo: required
dist: trusty
cache: ccache

services:
  - docker

before_install:
  - docker build -t ldallolio/vegaci .
  - docker run ldallolio/vegaci /bin/sh -c "cd /usr/local/src/vegapp/build; ctest ."

script:
    - ctest .
