var annotated_dup =
[
    [ "std", null, [
      [ "hash< vega::CellType >", "structstd_1_1hash_3_01vega_1_1CellType_01_4.html", "structstd_1_1hash_3_01vega_1_1CellType_01_4" ],
      [ "hash< vega::DOF >", "structstd_1_1hash_3_01vega_1_1DOF_01_4.html", "structstd_1_1hash_3_01vega_1_1DOF_01_4" ],
      [ "hash< vega::DOFS >", "structstd_1_1hash_3_01vega_1_1DOFS_01_4.html", "structstd_1_1hash_3_01vega_1_1DOFS_01_4" ],
      [ "hash< vega::Identifiable< T > >", "structstd_1_1hash_3_01vega_1_1Identifiable_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01vega_1_1Identifiable_3_01T_01_4_01_4" ],
      [ "hash< vega::Node >", "structstd_1_1hash_3_01vega_1_1Node_01_4.html", "structstd_1_1hash_3_01vega_1_1Node_01_4" ],
      [ "hash< vega::Reference< T > >", "structstd_1_1hash_3_01vega_1_1Reference_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01vega_1_1Reference_3_01T_01_4_01_4" ],
      [ "hash< vega::SpaceDimension >", "structstd_1_1hash_3_01vega_1_1SpaceDimension_01_4.html", "structstd_1_1hash_3_01vega_1_1SpaceDimension_01_4" ]
    ] ],
    [ "vega", null, [
      [ "aster", null, [
        [ "AsterModel", "classvega_1_1aster_1_1AsterModel.html", "classvega_1_1aster_1_1AsterModel" ],
        [ "AsterRunner", "classvega_1_1aster_1_1AsterRunner.html", "classvega_1_1aster_1_1AsterRunner" ],
        [ "AsterWriter", "classvega_1_1aster_1_1AsterWriter.html", "classvega_1_1aster_1_1AsterWriter" ]
      ] ],
      [ "nastran", null, [
        [ "Line", "classvega_1_1nastran_1_1Line.html", "classvega_1_1nastran_1_1Line" ],
        [ "NastranParser", "classvega_1_1nastran_1_1NastranParser.html", "classvega_1_1nastran_1_1NastranParser" ],
        [ "NastranRunner", "classvega_1_1nastran_1_1NastranRunner.html", "classvega_1_1nastran_1_1NastranRunner" ],
        [ "NastranTokenizer", "classvega_1_1nastran_1_1NastranTokenizer.html", "classvega_1_1nastran_1_1NastranTokenizer" ],
        [ "NastranWriter", "classvega_1_1nastran_1_1NastranWriter.html", "classvega_1_1nastran_1_1NastranWriter" ]
      ] ],
      [ "optistruct", null, [
        [ "OptistructParser", "classvega_1_1optistruct_1_1OptistructParser.html", "classvega_1_1optistruct_1_1OptistructParser" ]
      ] ],
      [ "systus", null, [
        [ "SystusMatrices", "classvega_1_1systus_1_1SystusMatrices.html", "classvega_1_1systus_1_1SystusMatrices" ],
        [ "SystusMatrix", "classvega_1_1systus_1_1SystusMatrix.html", "classvega_1_1systus_1_1SystusMatrix" ],
        [ "SystusModel", "classvega_1_1systus_1_1SystusModel.html", "classvega_1_1systus_1_1SystusModel" ],
        [ "SystusRunner", "classvega_1_1systus_1_1SystusRunner.html", "classvega_1_1systus_1_1SystusRunner" ],
        [ "SystusTable", "classvega_1_1systus_1_1SystusTable.html", "classvega_1_1systus_1_1SystusTable" ],
        [ "SystusWriter", "classvega_1_1systus_1_1SystusWriter.html", "classvega_1_1systus_1_1SystusWriter" ]
      ] ],
      [ "Analysis", "classvega_1_1Analysis.html", "classvega_1_1Analysis" ],
      [ "AnalysisParameter", "classvega_1_1AnalysisParameter.html", "classvega_1_1AnalysisParameter" ],
      [ "Assertion", "classvega_1_1Assertion.html", "classvega_1_1Assertion" ],
      [ "Beam", "classvega_1_1Beam.html", "classvega_1_1Beam" ],
      [ "BilinearElasticNature", "classvega_1_1BilinearElasticNature.html", "classvega_1_1BilinearElasticNature" ],
      [ "BoundaryCondition", "classvega_1_1BoundaryCondition.html", "classvega_1_1BoundaryCondition" ],
      [ "CartesianCoordinateSystem", "classvega_1_1CartesianCoordinateSystem.html", "classvega_1_1CartesianCoordinateSystem" ],
      [ "Cell", "classvega_1_1Cell.html", "classvega_1_1Cell" ],
      [ "CellContainer", "classvega_1_1CellContainer.html", "classvega_1_1CellContainer" ],
      [ "CellData", "classvega_1_1CellData.html", "classvega_1_1CellData" ],
      [ "CellGroup", "classvega_1_1CellGroup.html", "classvega_1_1CellGroup" ],
      [ "CellGroup2Families", "classvega_1_1CellGroup2Families.html", "classvega_1_1CellGroup2Families" ],
      [ "CellIterator", "classvega_1_1CellIterator.html", "classvega_1_1CellIterator" ],
      [ "CellStorage", "classvega_1_1CellStorage.html", "classvega_1_1CellStorage" ],
      [ "CellType", "classvega_1_1CellType.html", "classvega_1_1CellType" ],
      [ "CircularSectionBeam", "classvega_1_1CircularSectionBeam.html", "classvega_1_1CircularSectionBeam" ],
      [ "Composite", "classvega_1_1Composite.html", "classvega_1_1Composite" ],
      [ "CompositeLayer", "classvega_1_1CompositeLayer.html", "classvega_1_1CompositeLayer" ],
      [ "ConfigurationParameters", "classvega_1_1ConfigurationParameters.html", "classvega_1_1ConfigurationParameters" ],
      [ "ConstantValue", "classvega_1_1ConstantValue.html", "classvega_1_1ConstantValue" ],
      [ "Constraint", "classvega_1_1Constraint.html", "classvega_1_1Constraint" ],
      [ "ConstraintSet", "classvega_1_1ConstraintSet.html", "classvega_1_1ConstraintSet" ],
      [ "Continuum", "classvega_1_1Continuum.html", "classvega_1_1Continuum" ],
      [ "CoordinateSystem", "classvega_1_1CoordinateSystem.html", "classvega_1_1CoordinateSystem" ],
      [ "CoordinateSystemStorage", "classvega_1_1CoordinateSystemStorage.html", "classvega_1_1CoordinateSystemStorage" ],
      [ "CylindricalCoordinateSystem", "classvega_1_1CylindricalCoordinateSystem.html", "classvega_1_1CylindricalCoordinateSystem" ],
      [ "DampingMatrix", "classvega_1_1DampingMatrix.html", "classvega_1_1DampingMatrix" ],
      [ "Discrete", "classvega_1_1Discrete.html", "classvega_1_1Discrete" ],
      [ "DiscretePoint", "classvega_1_1DiscretePoint.html", "classvega_1_1DiscretePoint" ],
      [ "DiscreteSegment", "classvega_1_1DiscreteSegment.html", "classvega_1_1DiscreteSegment" ],
      [ "DOF", "classvega_1_1DOF.html", "classvega_1_1DOF" ],
      [ "DOFCoefs", "classvega_1_1DOFCoefs.html", "classvega_1_1DOFCoefs" ],
      [ "DOFMatrix", "classvega_1_1DOFMatrix.html", "classvega_1_1DOFMatrix" ],
      [ "DOFS", "classvega_1_1DOFS.html", "classvega_1_1DOFS" ],
      [ "DynamicExcitation", "classvega_1_1DynamicExcitation.html", "classvega_1_1DynamicExcitation" ],
      [ "DynaPhase", "classvega_1_1DynaPhase.html", "classvega_1_1DynaPhase" ],
      [ "ElasticNature", "classvega_1_1ElasticNature.html", "classvega_1_1ElasticNature" ],
      [ "ElementLoading", "classvega_1_1ElementLoading.html", "classvega_1_1ElementLoading" ],
      [ "ElementSet", "classvega_1_1ElementSet.html", "classvega_1_1ElementSet" ],
      [ "Family", "structvega_1_1Family.html", "structvega_1_1Family" ],
      [ "ForceLine", "classvega_1_1ForceLine.html", "classvega_1_1ForceLine" ],
      [ "ForceSurface", "classvega_1_1ForceSurface.html", "classvega_1_1ForceSurface" ],
      [ "FrequencyAssertion", "classvega_1_1FrequencyAssertion.html", "classvega_1_1FrequencyAssertion" ],
      [ "FrequencyBand", "classvega_1_1FrequencyBand.html", "classvega_1_1FrequencyBand" ],
      [ "FrequencyList", "classvega_1_1FrequencyList.html", "classvega_1_1FrequencyList" ],
      [ "FrequencyRange", "classvega_1_1FrequencyRange.html", "classvega_1_1FrequencyRange" ],
      [ "Function", "classvega_1_1Function.html", "classvega_1_1Function" ],
      [ "FunctionTable", "classvega_1_1FunctionTable.html", "classvega_1_1FunctionTable" ],
      [ "Gap", "classvega_1_1Gap.html", "classvega_1_1Gap" ],
      [ "GapNodeDirection", "classvega_1_1GapNodeDirection.html", "classvega_1_1GapNodeDirection" ],
      [ "GapTwoNodes", "classvega_1_1GapTwoNodes.html", "classvega_1_1GapTwoNodes" ],
      [ "GenericSectionBeam", "classvega_1_1GenericSectionBeam.html", "classvega_1_1GenericSectionBeam" ],
      [ "Globals", "classvega_1_1Globals.html", "classvega_1_1Globals" ],
      [ "Gravity", "classvega_1_1Gravity.html", "classvega_1_1Gravity" ],
      [ "Group", "classvega_1_1Group.html", "classvega_1_1Group" ],
      [ "HomogeneousConstraint", "classvega_1_1HomogeneousConstraint.html", "classvega_1_1HomogeneousConstraint" ],
      [ "Identifiable", "classvega_1_1Identifiable.html", "classvega_1_1Identifiable" ],
      [ "InitialTemperature", "classvega_1_1InitialTemperature.html", "classvega_1_1InitialTemperature" ],
      [ "ISectionBeam", "classvega_1_1ISectionBeam.html", "classvega_1_1ISectionBeam" ],
      [ "LinearDynaModalFreq", "classvega_1_1LinearDynaModalFreq.html", "classvega_1_1LinearDynaModalFreq" ],
      [ "LinearMecaStat", "classvega_1_1LinearMecaStat.html", "classvega_1_1LinearMecaStat" ],
      [ "LinearModal", "classvega_1_1LinearModal.html", "classvega_1_1LinearModal" ],
      [ "LinearMultiplePointConstraint", "classvega_1_1LinearMultiplePointConstraint.html", "classvega_1_1LinearMultiplePointConstraint" ],
      [ "Lmpc", "classvega_1_1Lmpc.html", "classvega_1_1Lmpc" ],
      [ "Loading", "classvega_1_1Loading.html", "classvega_1_1Loading" ],
      [ "LoadSet", "classvega_1_1LoadSet.html", "classvega_1_1LoadSet" ],
      [ "MassMatrix", "classvega_1_1MassMatrix.html", "classvega_1_1MassMatrix" ],
      [ "Material", "classvega_1_1Material.html", "classvega_1_1Material" ],
      [ "MatrixElement", "classvega_1_1MatrixElement.html", "classvega_1_1MatrixElement" ],
      [ "Mesh", "classvega_1_1Mesh.html", "classvega_1_1Mesh" ],
      [ "ModalDamping", "classvega_1_1ModalDamping.html", "classvega_1_1ModalDamping" ],
      [ "Model", "classvega_1_1Model.html", "classvega_1_1Model" ],
      [ "ModelConfiguration", "classvega_1_1ModelConfiguration.html", "classvega_1_1ModelConfiguration" ],
      [ "ModelType", "classvega_1_1ModelType.html", "classvega_1_1ModelType" ],
      [ "NamedValue", "classvega_1_1NamedValue.html", "classvega_1_1NamedValue" ],
      [ "Nature", "classvega_1_1Nature.html", "classvega_1_1Nature" ],
      [ "NodalAssertion", "classvega_1_1NodalAssertion.html", "classvega_1_1NodalAssertion" ],
      [ "NodalComplexDisplacementAssertion", "classvega_1_1NodalComplexDisplacementAssertion.html", "classvega_1_1NodalComplexDisplacementAssertion" ],
      [ "NodalDisplacementAssertion", "classvega_1_1NodalDisplacementAssertion.html", "classvega_1_1NodalDisplacementAssertion" ],
      [ "NodalForce", "classvega_1_1NodalForce.html", "classvega_1_1NodalForce" ],
      [ "NodalForceFourNodes", "classvega_1_1NodalForceFourNodes.html", "classvega_1_1NodalForceFourNodes" ],
      [ "NodalForceTwoNodes", "classvega_1_1NodalForceTwoNodes.html", "classvega_1_1NodalForceTwoNodes" ],
      [ "NodalMass", "classvega_1_1NodalMass.html", "classvega_1_1NodalMass" ],
      [ "Node", "classvega_1_1Node.html", "classvega_1_1Node" ],
      [ "NodeContainer", "classvega_1_1NodeContainer.html", "classvega_1_1NodeContainer" ],
      [ "NodeData", "classvega_1_1NodeData.html", "classvega_1_1NodeData" ],
      [ "NodeGroup", "classvega_1_1NodeGroup.html", "classvega_1_1NodeGroup" ],
      [ "NodeGroup2Families", "classvega_1_1NodeGroup2Families.html", "classvega_1_1NodeGroup2Families" ],
      [ "NodeIterator", "classvega_1_1NodeIterator.html", "classvega_1_1NodeIterator" ],
      [ "NodeLoading", "classvega_1_1NodeLoading.html", "classvega_1_1NodeLoading" ],
      [ "NodeStorage", "classvega_1_1NodeStorage.html", "classvega_1_1NodeStorage" ],
      [ "NonLinearElasticNature", "classvega_1_1NonLinearElasticNature.html", "classvega_1_1NonLinearElasticNature" ],
      [ "NonLinearMecaStat", "classvega_1_1NonLinearMecaStat.html", "classvega_1_1NonLinearMecaStat" ],
      [ "NonLinearStrategy", "classvega_1_1NonLinearStrategy.html", "classvega_1_1NonLinearStrategy" ],
      [ "NormalPressionFace", "classvega_1_1NormalPressionFace.html", "classvega_1_1NormalPressionFace" ],
      [ "Objective", "classvega_1_1Objective.html", "classvega_1_1Objective" ],
      [ "OrientationCoordinateSystem", "classvega_1_1OrientationCoordinateSystem.html", "classvega_1_1OrientationCoordinateSystem" ],
      [ "OrthotropicNature", "classvega_1_1OrthotropicNature.html", "classvega_1_1OrthotropicNature" ],
      [ "Parser", "classvega_1_1Parser.html", "classvega_1_1Parser" ],
      [ "ParsingException", "classvega_1_1ParsingException.html", "classvega_1_1ParsingException" ],
      [ "PressionFaceTwoNodes", "classvega_1_1PressionFaceTwoNodes.html", "classvega_1_1PressionFaceTwoNodes" ],
      [ "QuasiRigidConstraint", "classvega_1_1QuasiRigidConstraint.html", "classvega_1_1QuasiRigidConstraint" ],
      [ "Rbar", "classvega_1_1Rbar.html", "classvega_1_1Rbar" ],
      [ "Rbe3", "classvega_1_1Rbe3.html", "classvega_1_1Rbe3" ],
      [ "RBE3", "classvega_1_1RBE3.html", "classvega_1_1RBE3" ],
      [ "RectangularSectionBeam", "classvega_1_1RectangularSectionBeam.html", "classvega_1_1RectangularSectionBeam" ],
      [ "Reference", "classvega_1_1Reference.html", "classvega_1_1Reference" ],
      [ "ResultReader", "classvega_1_1ResultReader.html", "classvega_1_1ResultReader" ],
      [ "RigidConstraint", "classvega_1_1RigidConstraint.html", "classvega_1_1RigidConstraint" ],
      [ "RigidNature", "classvega_1_1RigidNature.html", "classvega_1_1RigidNature" ],
      [ "RigidSet", "classvega_1_1RigidSet.html", "classvega_1_1RigidSet" ],
      [ "Rotation", "classvega_1_1Rotation.html", "classvega_1_1Rotation" ],
      [ "RotationCenter", "classvega_1_1RotationCenter.html", "classvega_1_1RotationCenter" ],
      [ "RotationNode", "classvega_1_1RotationNode.html", "classvega_1_1RotationNode" ],
      [ "Runner", "classvega_1_1Runner.html", "classvega_1_1Runner" ],
      [ "ScalarSpring", "classvega_1_1ScalarSpring.html", "classvega_1_1ScalarSpring" ],
      [ "Shell", "classvega_1_1Shell.html", "classvega_1_1Shell" ],
      [ "SinglePointConstraint", "classvega_1_1SinglePointConstraint.html", "classvega_1_1SinglePointConstraint" ],
      [ "Solver", "classvega_1_1Solver.html", "classvega_1_1Solver" ],
      [ "SpaceDimension", "classvega_1_1SpaceDimension.html", "classvega_1_1SpaceDimension" ],
      [ "SpreadRange", "classvega_1_1SpreadRange.html", "classvega_1_1SpreadRange" ],
      [ "StaticPressure", "classvega_1_1StaticPressure.html", "classvega_1_1StaticPressure" ],
      [ "StepRange", "classvega_1_1StepRange.html", "classvega_1_1StepRange" ],
      [ "StiffnessMatrix", "classvega_1_1StiffnessMatrix.html", "classvega_1_1StiffnessMatrix" ],
      [ "StructuralSegment", "classvega_1_1StructuralSegment.html", "classvega_1_1StructuralSegment" ],
      [ "Tokenizer", "classvega_1_1Tokenizer.html", "classvega_1_1Tokenizer" ],
      [ "Value", "classvega_1_1Value.html", "classvega_1_1Value" ],
      [ "ValueOrReference", "classvega_1_1ValueOrReference.html", "classvega_1_1ValueOrReference" ],
      [ "ValuePlaceHolder", "classvega_1_1ValuePlaceHolder.html", "classvega_1_1ValuePlaceHolder" ],
      [ "ValueRange", "classvega_1_1ValueRange.html", "classvega_1_1ValueRange" ],
      [ "VectorialFunction", "classvega_1_1VectorialFunction.html", "classvega_1_1VectorialFunction" ],
      [ "VectorialValue", "classvega_1_1VectorialValue.html", "classvega_1_1VectorialValue" ],
      [ "VegaCommandLine", "classvega_1_1VegaCommandLine.html", "classvega_1_1VegaCommandLine" ],
      [ "Writer", "classvega_1_1Writer.html", "classvega_1_1Writer" ],
      [ "WritingException", "classvega_1_1WritingException.html", "classvega_1_1WritingException" ]
    ] ]
];