FROM ldallolio/vegaci

MAINTAINER Alter Ego Engineering <contact@aego.ai>

USER vega
ENV VEGA_SOURCE=/home/vega/vegapp
ENV VEGA_BUILD=$VEGA_SOURCE/build
COPY --chown=vega:vega . $VEGA_SOURCE
RUN mkdir $VEGA_BUILD
WORKDIR $VEGA_BUILD
RUN source /home/vega/.bashrc && cmake -DCMAKE_BUILD_TYPE=SRelease .. && make -j
