FROM ldallolio/vegaci

MAINTAINER Alter Ego Engineering <contact@aego.ai>

USER vega
ENV VEGA_SOURCE=/home/vega/vegapp
ENV VEGA_BUILD=$VEGA_SOURCE/build
COPY --chown=vega:vega . $VEGA_SOURCE
RUN mkdir $VEGA_BUILD
WORKDIR $VEGA_BUILD
RUN source /home/vega/.bashrc && cmake -DCMAKE_BUILD_TYPE=SDebug -DRUN_SYSTUS=ON .. && make -j && ctest .

#FROM scratch
#COPY --from=0 /home/vega/vegapp/build/bin/vegapp /
#CMD ["/vegapp"]
